theme = "autumn"

[editor]
rulers = [80, 100, 120]
trim-trailing-whitespace = true
trim-final-newlines = true

[editor.whitespace]
render = "all"

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = false
